@startuml

!include <office/Communications/3rd_party_call_center_solution.puml>
!include <office/Communications/3rd_party_integration.puml>
!include <office/Communications/3rd_party_service.puml>
!include <office/Communications/application_sharing_workload.puml>
!include <office/Communications/audio_conferencing_application.puml>
!include <office/Communications/central_management_service.puml>
!include <office/Communications/chat_room.puml>
!include <office/Communications/conference_announcement_service.puml>
!include <office/Communications/disconnected_mailbox.puml>
!include <office/Communications/discovery_search_mailbox.puml>
!include <office/Communications/dynamic_distribution_group.puml>
!include <office/Communications/edge_subscription.puml>
!include <office/Communications/email_workload.puml>
!include <office/Communications/equipment_mailbox.puml>
!include <office/Communications/exchange_active_sync_blue.puml>
!include <office/Communications/exchange_active_sync.puml>
!include <office/Communications/fax_partner.puml>
!include <office/Communications/global_address_list.puml>
!include <office/Communications/hybrid_voip_gateway.puml>
!include <office/Communications/im_workload.puml>
!include <office/Communications/journaling_rule.puml>
!include <office/Communications/local_move_request.puml>
!include <office/Communications/lync_control_panel.puml>
!include <office/Communications/lync_phone_edition.puml>
!include <office/Communications/lync_room_system.puml>
!include <office/Communications/lync_server_management_tool.puml>
!include <office/Communications/lync_storage_service.puml>
!include <office/Communications/lync_web_app_client.puml>
!include <office/Communications/mailbox_assistant.puml>
!include <office/Communications/mail_enabled_public_folder.puml>
!include <office/Communications/messages_queued.puml>
!include <office/Communications/offline_address_book.puml>
!include <office/Communications/personal_archive_mailbox.puml>
!include <office/Communications/public_im_cloud_service.puml>
!include <office/Communications/push_notification_service.puml>
!include <office/Communications/queue_viewer.puml>
!include <office/Communications/remote_mailbox.puml>
!include <office/Communications/remote_move_request.puml>
!include <office/Communications/response_group.puml>
!include <office/Communications/response_group_service.puml>
!include <office/Communications/room_mailbox.puml>
!include <office/Communications/shared_mailbox.puml>
!include <office/Communications/sip_uri_um_dial_plan.puml>
!include <office/Communications/site_mailbox.puml>
!include <office/Communications/skype_for_business_control_panel.puml>
!include <office/Communications/skype_for_business_phone_edition.puml>
!include <office/Communications/skype_for_business_room_system.puml>
!include <office/Communications/skype_for_business_server_management_tool.puml>
!include <office/Communications/skype_for_business_storage_service.puml>
!include <office/Communications/skype_for_business_web_app_client.puml>
!include <office/Communications/sms_gateway.puml>
!include <office/Communications/smtp_connector.puml>
!include <office/Communications/system_mailbox.puml>
!include <office/Communications/tdm_pbx.puml>
!include <office/Communications/telephone_extension_dial_plan.puml>
!include <office/Communications/transport_rule.puml>
!include <office/Communications/ucma_application.puml>
!include <office/Communications/ucwa_application.puml>
!include <office/Communications/um_auto_attendant.puml>
!include <office/Communications/um_dial_plan_e164.puml>
!include <office/Communications/um_dial_plan_secondary.puml>
!include <office/Communications/um_enabled_mailbox.puml>
!include <office/Communications/um_hunt_group.puml>
!include <office/Communications/um_ip_gateway.puml>
!include <office/Communications/user_mailbox.puml>
!include <office/Communications/video_workload.puml>
!include <office/Communications/voice_mail_preview_partner.puml>
!include <office/Communications/voice_workload.puml>
!include <office/Communications/voip_gateway.puml>
!include <office/Communications/watcher_node.puml>
!include <office/Communications/xmpp_service.puml>

@enduml
