@startuml

!include <office/Servers/3rd_party_mail_server.puml>
!include <office/Servers/active_directory_federation_services_proxy.puml>
!include <office/Servers/active_directory_federation_services_server_blue.puml>
!include <office/Servers/active_directory_federation_services_server_ghosted.puml>
!include <office/Servers/active_directory_federation_services_server_green.puml>
!include <office/Servers/active_directory_federation_services_server_orange.puml>
!include <office/Servers/active_directory_federation_services_server.puml>
!include <office/Servers/application_server_blue.puml>
!include <office/Servers/application_server_ghosted.puml>
!include <office/Servers/application_server_green.puml>
!include <office/Servers/application_server_orange.puml>
!include <office/Servers/application_server.puml>
!include <office/Servers/call_admission_control_service.puml>
!include <office/Servers/certificate_authority.puml>
!include <office/Servers/cluster_server_blue.puml>
!include <office/Servers/cluster_server_ghosted.puml>
!include <office/Servers/cluster_server_green.puml>
!include <office/Servers/cluster_server_orange.puml>
!include <office/Servers/cluster_server.puml>
!include <office/Servers/database_server_blue.puml>
!include <office/Servers/database_server_ghosted.puml>
!include <office/Servers/database_server_green.puml>
!include <office/Servers/database_server_orange.puml>
!include <office/Servers/database_server.puml>
!include <office/Servers/datacenter.puml>
!include <office/Servers/dirsync_server.puml>
!include <office/Servers/domain_controller.puml>
!include <office/Servers/exchange_2010_client_access_server_role.puml>
!include <office/Servers/exchange_2010_edge_transport_server_role.puml>
!include <office/Servers/exchange_2010_hub_transport_server_role.puml>
!include <office/Servers/exchange_2010_mailbox_server_role.puml>
!include <office/Servers/exchange_2010_um_server_role.puml>
!include <office/Servers/exchange_2013_client_access_server.puml>
!include <office/Servers/exchange_2013_edge_transport_server.puml>
!include <office/Servers/exchange_2013_mailbox_server.puml>
!include <office/Servers/exchange_2013_server.puml>
!include <office/Servers/file_server.puml>
!include <office/Servers/hybrid_server.puml>
!include <office/Servers/mainframe_host.puml>
!include <office/Servers/mainframe.puml>
!include <office/Servers/monitoring_sql_reporting_services.puml>
!include <office/Servers/network.puml>
!include <office/Servers/office_web_apps_server.puml>
!include <office/Servers/on_premises_server.puml>
!include <office/Servers/physical_host_farm_solid_blue.puml>
!include <office/Servers/physical_host_solid_blue.puml>
!include <office/Servers/reverse_proxy.puml>
!include <office/Servers/scom.puml>
!include <office/Servers/server_disaster.puml>
!include <office/Servers/server_farm_blue.puml>
!include <office/Servers/server_farm_ghosted.puml>
!include <office/Servers/server_farm_green.puml>
!include <office/Servers/server_farm_orange.puml>
!include <office/Servers/server_farm.puml>
!include <office/Servers/server_generic_blue.puml>
!include <office/Servers/server_generic_ghosted.puml>
!include <office/Servers/server_generic_green.puml>
!include <office/Servers/server_generic_orange.puml>
!include <office/Servers/server_generic.puml>
!include <office/Servers/server_side_code.puml>
!include <office/Servers/sharepoint_server.puml>
!include <office/Servers/skype_for_business_back_end_server_mirror.puml>
!include <office/Servers/skype_for_business_back_end_server.puml>
!include <office/Servers/skype_for_business_director_array.puml>
!include <office/Servers/skype_for_business_director.puml>
!include <office/Servers/skype_for_business_edge_server_pool.puml>
!include <office/Servers/skype_for_business_edge_server.puml>
!include <office/Servers/skype_for_business_front_end_pool.puml>
!include <office/Servers/skype_for_business_front_end_server.puml>
!include <office/Servers/skype_for_business_mediation_server.puml>
!include <office/Servers/skype_for_business_monitoring_server.puml>
!include <office/Servers/skype_for_business_persistent_chat_server.puml>
!include <office/Servers/skype_for_business_server.puml>
!include <office/Servers/sql_server.puml>
!include <office/Servers/survivable_branch_appliance.puml>
!include <office/Servers/survivable_branch_server.puml>
!include <office/Servers/topology_builder.puml>
!include <office/Servers/trusted_application_pool.puml>
!include <office/Servers/trusted_application_server.puml>
!include <office/Servers/tunnel_angled.puml>
!include <office/Servers/tunnel_straight.puml>
!include <office/Servers/video_interop_server.puml>
!include <office/Servers/virtual_application_server_blue.puml>
!include <office/Servers/virtual_application_server.puml>
!include <office/Servers/virtual_database_server_blue.puml>
!include <office/Servers/virtual_database_server.puml>
!include <office/Servers/virtual_server_blue.puml>
!include <office/Servers/virtual_server.puml>
!include <office/Servers/virtual_web_server_blue.puml>
!include <office/Servers/virtual_web_server.puml>
!include <office/Servers/voicemail_preview_partner.puml>
!include <office/Servers/web_server_blue.puml>
!include <office/Servers/web_server_ghosted.puml>
!include <office/Servers/web_server_green.puml>
!include <office/Servers/web_server_orange.puml>
!include <office/Servers/web_server.puml>
!include <office/Servers/windows_router.puml>
!include <office/Servers/windows_server.puml>

@enduml
